site_name: KidsPay

nav:
    - KidsPay: index.md
    - À Propos: about.md

theme:
  name: readthedocs
  custom_dir: custom/

site_author: Keany Vy KHUN

site_favicon: favicon.ico

copyright: © Copyright 2020, KidsPay.
