site_name: KidsPay

nav:
    - KidsPay: index.md
    - À Propos: about.md

theme:
  name: readthedocs
  custom_dir: custom/
  colorscheme: github
  highlightjs: true
  shortcuts:
    help: 72    # h (help)
    next: 83     # s (suivant)
    previous: 80 # p (précédent)
    search: 82   # r (rechercher)

prev_next_buttons_location: top

site_author: Keany Vy KHUN

site_favicon: favicon.ico

markdown_extensions:
  - admonition

copyright: © Copyright 2020, KidsPay.
